### ISSUE TITLE
Factor out external dependencies

### ISSUE THREAD

**Issue by magiconair** [spf13/cobra#195]
I was trying to use cobra in one of my projects and I've noticed that cobra depends on a couple of libraries don't really belong to the core. The reason I'm bringing this up is because I'm managing my deps manually via vendoring into a sub dir and separate commits per lib. It feels a bit odd to copy dependencies which I don't need but cobra won't compile without them.

The libraries in question are:

`github.com/inconshreveable/mousetrap` 
`github.com/cpuguy83/go-md2man/md2man`

The first one is only needed on Windows and the second one only for the man page generation. The man and markdown generation also seems needlessly tied to the `cobra.Command` object. 

Both of them can be factored out either with conditional compilation (for mousetrap) or move the code into a sub directory (man and md generation).

I have PRs ready for both refactorings but would like to know whether this is in line with the project.

**Comment by magiconair** [comment]
I forgot to mention that 

`github.com/cpuguy83/go-md2man/md2man`

itself has two additional dependencies

```
github.com/shurcooL/sanitized_anchor_name
github.com/russross/blackfriday
```

**Comment by bep** [comment]
This makes totally sense to me. @eparis and @spf13 might have something to say about it.

**Comment by apriendeau** [comment]
Well I know that even hugo uses `github.com/russross/blackfriday`. I could see removing `mousetrap` but blackfriday is pretty amazing all around. So would this remove the all the dependencies or just the two that you mentioned?

**Comment by spf13** [comment]
I'm a bit confused about why people have issues with "unneeded dependencies". If you are using a tool to manage your dependencies it doesn't matter if there are 2 or 20. The binary itself isn't slower or heavier because of unused dependencies. 

While we could optimize for fewer included dependencies we would do so at a high cost of integrating cobra significantly harder. 

Please help me understand why this is an issue.

**Comment by bep** [comment]
I'm totally in line with the thread starter here.

>If you are using a tool to manage your dependencies it doesn't matter if there are 2 or 20. 

There no perfect tool for that. They may handle the versioning etc., but if you drag a dependency into your project you would still have to do a QA about its license and quality etc. Normally not an issue in a personal toy project, but certainly a issue in commercial software.

>The binary itself isn't slower or heavier because of unused dependencies. 

It will be bigger?

>... a high cost of integrating cobra significantly harder. 

As I understand it, the core functionality of Cobra will be left untouched: CLI. The extras man/doc generation is ... extras that is normally not needed for the running application. Having to do an extra "blank import" or similar to use these extras doesn't sound hard to me.

**Comment by magiconair** [comment]
The changes I've made are as follows:

1. `github.com/inconshreveable/mousetrap` is only compiled on windows. So nothing changes except that you can now compile `cobra` without `mousetrap` on non-windows platforms.

* doc generation is moved to a `doc` package and instead of calling `cmd.GetMan()` you call `doc.GetMan(cmd)` (same for markdown). This means that if I don't want/need the doc package I also don't need it's dependencies to compile `cobra`. Please note, that this is already possible with the current code. `cmd.GetMan()` just calls `GetMan(cmd, ...)`.

So, yes the `doc` change will break existing code since they need to import a sub package and change the call but IMHO this won't make it more difficult to integrate `cobra` into existing packages.

As for the motivation:

The problem is not with the binary getting bigger. The compiler will strip that away. 

The problem is that every dependency has a cost. By adding it to `cobra` you now require every user of `cobra` to import and manage these dependencies in their environments whether they need/want the functionality or not. `cobra` does not mention which versions of these libraries are compatible. The `md2man` readme for example says that this is "Work in progress". You require every developer to trust that this library is OK to include in their code since `cobra` won't compile without it. (I am not bashing `md2man` here. Just trying to make a point)

If you look at the code of the doc generation then you see very little overlap between the doc generation and the core of `cobra` which is a good indication that this should live in its own package. The original signatures also indicate that they did initially. 

If these libraries are essential to `cobra` you could add a private copy of them to `cobra`. Since this isn't the case each developer has to make this assessment which is in essence what I'm doing. 

Go does not have a package manager and versioned imports for a reason. This is not an oversight. The main motivation is because you cannot solve the problem of transitive dependencies automatically. The developer has to do that. That's also why it would be a bad idea if `hugo` actually depended on the transitive dependency of `blackfriday` provided by `cobra` -> `md2man`. What if `hugo` needs a version of `blackfriday` that is incompatible with the version provided by `cobra`?

As for my own case: 

I'm trying to integrate `cobra` into our main tool set which consists of a single repo which we use to generate about 40 executables. All dependencies are vendored in with a separate commit per library. We don't need a tool for that since we rarely touch them. We also don't want a tool for that to make library import not too trivial so that people don't throw in libs for good measure. That's one of the lessons we've learned from the Java project we're porting to Go where we have lots of dependencies with all kinds of different versions. 

I want to use `cobra` since I think it is a good tool for CLI processing. I also think that the man page and markdown generation is a cool idea for someone who needs it. However, I don't think that every user should be forced to include this functionality for the reasons I've just described and it can be fixed with a simple refactor.

I understand that dependency management is a hot topic in the Go community hence the question before the PR.

I hope that wasn't too long and explains the motivation :)

**Comment by apriendeau** [comment]
I would disagree that it's not an oversight, because of them adding
GOVENDOREXPERIMENT but I am also not opposed completely to removing them
but the red flag for me is the API change.

This keeps coming up, is there a roadmap to clean these up @spf13? Maybe
include this change when that happens?

**Comment by magiconair** [comment]
@apriendeau All that the GOVENDOREXPERIMENT provides is to allow you to have a private copy of your dependencies in a sub directory without having to rewrite the import path. You can achieve the same with rewriting the import paths today. I'd argue that this will make it simpler for people to throw in libraries into a project just because they can and it is easy instead of pushing for better and more orthogonal library design so that this problem doesn't exist in the first place.

**Comment by bep** [comment]
The API change in this is minimal. The fix in Hugo, one of fairly few users of the extended features we talk about here, will be a 20 second code change.

**Comment by magiconair** [comment]
If that

```
grep -r --include='*.go' GenMa *
commands/gendoc.go:		cobra.GenMarkdownTreeCustom(cmd.Root(), gendocdir, prepender, linkHandler)
commands/genman.go:		header := &cobra.GenManHeader{
commands/genman.go:		cmd.Root().GenManTree(header, genmandir)
```

**Comment by anthonyfok** [comment]
>> The API change in this is minimal. The fix in Hugo, one of fairly few users of the extended features we talk about here, will be a 20 second code change.
> If that
>
>        grep -r --include='*.go' GenMa *
> ...

I literally bursted out laughing...

Though for a split second I thought it was an automatic `sed` command that makes the changes in split second... :wink:  Nevertheless, impressive enough.  &lt;grin, duck, run&gt;...

**Comment by apriendeau** [comment]
Hey, I never said it was big API change... just said its an instant red flag, mainly to double check before we do it. :smile: I am not opposed to API changes in the slightest. Embrace the future and break all the things! ;)

**Comment by spf13** [comment]
Just need to let the kubernetes guys know first

**Comment by magiconair** [comment]
I've submitted the PRs for code review. Commit messages should indicate the changes. Feel free to comment. The only thing I'm a bit torn is the duplication of the test setup for the doc generation but it works.

1. Either leave as is (duplicated)
2. Export vars in cobra test files
3. Move test setup to separate package (e.g. internal/test)

**Comment by spf13** [comment]
I appreciate the effort and direction here and I believe I understand your needs. 

Would it be sufficient to embed the dependent libraries in cobra so they are no longer dependencies? I've been meaning to vendor our dependencies anyway and that seems like it would solve your issues without changing the API at all. 

Thoughts?

**Comment by magiconair** [comment]
@spf13 Sure that would solve my issue although I would prefer `cobra` to be a lean CLI with an orthogonal design. The doc generation is an extension IMHO since the CLI works fine without it but not without lets say `pflag`. It should have probably not been a method on `Command` to begin with. 

If this was my project I would vendor in the libraries but still move the doc generation into a separate package since the API change is minimal and better design trumps the small change for your users. I think they can manage. The doc gen code could also use some love.

In the end this is your project and you have to make the final call.

**Comment by spf13** [comment]
@magiconair . I like the way you think. Yup. I think this approach is better and combined with vendoring it's a clean approach.

**Comment by eparis** [comment]
I am the kubernetes guy, I'll have no trouble handling that API change.

**Comment by eparis** [comment]
although if we are going to start API busting, is it time to just start busting? Throw out Run(), rework subcommand/args logic, rework error handling logic, I know there way more...

**Comment by magiconair** [comment]
I think compared to that my change falls under API tweaking.

**Comment by apriendeau** [comment]
@eparis, that's why I brought up what I did. I would love to kill Run and all of that. Sign me up! :+1:

**Comment by magiconair** [comment]
What's wrong with `Run` if I may ask?

**Comment by apriendeau** [comment]
If you look at RunE, it just merely allows you to populate the error to the top so you can handle all the errors out of execute.

**Comment by spf13** [comment]
Just to keep things sane, let's release Hugo 0.15. Have Thanksgiving and then let's break stuff.

**Comment by spf13** [comment]
It's also probably a good idea to have a release before breaking stuff.

**Comment by apriendeau** [comment]
Holidays are the best time to release though! I was going to vote Thursday at 2pm during the carving of the turkey. ;-). But in all seriousness, sounds like a good plan.

**Comment by bep** [comment]
I thought Thanksgiving was all about breaking stuff! :-)

**Comment by vjeantet** [comment]
Hello seems to break Hugo --> 

```
spf13/hugo/commands/gendoc.go:70: undefined: cobra.GenMarkdownTreeCustom
spf13/hugo/commands/genman.go:35: undefined: cobra.GenManHeader
spf13/hugo/commands/genman.go:50: cmd.Root().GenManTree undefined (type *cobra.Command has no field or method GenManTree)
```

**Comment by spf13** [comment]
I've updated it and it now works. You just caught it in the short state where one library was updated and the app wasn't. Thanks for catching it :)

**Comment by spf13** [comment]
I'm going to call this issue closed now. We can open new issues for breaking other things, but I think the scope of this one is done with #198 being merged in.

**Comment by vjeantet** [comment]
Which branch did you updated ? hugo "master" still can not be built.
Thanks for updating so quickly.

**Comment by spf13** [comment]
oh. you are right. I updated the wrong branch. I've now updated master. Please confirm on your side.

**Comment by vjeantet** [comment]
it works, thanks ! :gift:
