### PR TITLE
Update stale.yml

### PR DESCRIPTION
**Pull request by enrichman**
Fix typo

### CODE REVIEW

**Review by marckhouzam — APPROVED** [review]
Thanks @enrichman !

**Comment by marckhouzam** [comment]
The go 1.15 test is failing with 
```
../../../go/pkg/mod/github.com/kyoh86/richgo@v0.3.11/config/load.go:64:9: undefined: os.ReadFile
```
Looks like `richgo` 0.3.11, which was released 6 days ago, requires go 1.16.
We probably need to fix the version to 0.3.10 to continue working with go 1.15

@umarcor what do you think?

Since it is unrelated to the PR I will merge anyway.

**Comment by enrichman** [comment]
@marckhouzam you're welcome, thanks for the quick review!

**Comment by umarcor** [comment]
@marckhouzam go 1.15 is EOL. I believe we can remove it from the CI. However, this repo has a very unclear criteria to deprecate golang versions. In theory, https://github.com/spf13/cobra/blob/main/CONDUCT.md#deprecation. In practice, it's arbitrary upon how do maintainers (or employers) feel.

**Comment by marckhouzam** [comment]
Let's move the discussion to #1864
